name       : python-nose
version    : 1.3.7
release    : 8
source     :
    - https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz : f1bffef9cbc82628f6e7d7b40d7e255aefaa1adb6a1b1d26c69a8b79e6208a98
license    : LGPL-2.1
component  : programming.python
summary    : nose is nicer testing for python
description: |
    nose is nicer testing for python
builddeps  :
    - python-build
    - python-coverage
    - python-installer
    - python-wheel
setup      : |
    %patch -p1 -i $pkgfiles/python-nose-coverage4.patch
    %patch -p1 -i $pkgfiles/python-nose-py35.patch
    %patch -p1 -i $pkgfiles/python-nose-unicode.patch
    %patch -p1 -i $pkgfiles/python-nose-readunicode.patch
    %patch -p1 -i $pkgfiles/python-nose-py36.patch
    %patch -p1 -i $pkgfiles/python-nose-py38.patch
    %patch -p1 -i $pkgfiles/python-nose-no-use_2to3.patch
    2to3 --write --nobackups --no-diffs .
    2to3 --write --nobackups --no-diffs -d $(find . -name '*.rst')
build      : |
    %python3_setup
    python3 setup.py build_tests
install    : |
    %python3_install
check      : |
    python3 selftest.py
