name       : python-nose
version    : 1.3.7
release    : 3
source     :
    - https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz : f1bffef9cbc82628f6e7d7b40d7e255aefaa1adb6a1b1d26c69a8b79e6208a98
license    : LGPL-2.1
component  : programming.python
summary    : nose is nicer testing for python
description: |
    nose is nicer testing for python
builddeps  :
    - python-setuptools
setup      : |
    # https://github.com/nose-devs/nose/pull/983
    %patch -p1 < $pkgfiles/python-nose-py35.patch
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python selftest.py
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py build_tests
        python3 selftest.py
    popd
