name       : python-nose
version    : 1.3.7
release    : 1
source     :
    - https://pypi.python.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz : f1bffef9cbc82628f6e7d7b40d7e255aefaa1adb6a1b1d26c69a8b79e6208a98
license    : LGPL-2.1
component  : programming.python
summary    : nose is nicer testing for python
description: |
    nose is nicer testing for python
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
