name       : python-nose
version    : 1.3.7
release    : 7
source     :
    - https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz : f1bffef9cbc82628f6e7d7b40d7e255aefaa1adb6a1b1d26c69a8b79e6208a98
license    : LGPL-2.1
component  : programming.python
summary    : nose is nicer testing for python
description: |
    nose is nicer testing for python
builddeps  :
    - python-setuptools
setup      : |
    # https://github.com/nose-devs/nose/pull/983
    %patch -p1 < $pkgfiles/python-nose-py35.patch
    # setuptools 58 removed support for 2to3
    sed -i "s/'use_2to3': True,//" setup.py
    sed -i 's/from setuptools.command.build_py import Mixin2to3/from distutils.util import Mixin2to3/' setup3lib.py
    sed -i 's/except ImportError:/except IOError:/' setup.py
build      : |
    %python_setup
    2to3 -wn nose unit_tests functional_tests
    %python3_setup
install    : |
    %python_install
    %python3_install
    ## ???
    #ln -s /usr/bin/nosetests $installdir/usr/bin/nosetests-3.10
#check      : |
#    pushd $PKG_BUILD_DIR/py2build
#        python selftest.py
#    popd#
#
#    pushd $PKG_BUILD_DIR/py3build
#        #python3 setup.py build_tests
#        #python3 selftest.py
#s    popd
